### ISSUE TITLE
make 失败

### ISSUE THREAD

**Issue by briteming** [hchen90/jackpot#1]
hi.

git clone https://github.com/hchen90/jackpot
cd jackpot
cmake .
显示：
...
-- Configuring done
-- Generating done

于是，
make
显示：
Scanning dependencies of target jackpot
[  8%] Building CXX object src/CMakeFiles/jackpot.dir/client.cpp.o
clang: error: argument unused during compilation: '-rdynamic' [-Werror,-Wunused-command-line-argument]
make[2]: *** [src/CMakeFiles/jackpot.dir/client.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/jackpot.dir/all] Error 2
make: *** [all] Error 2

怎么解决？

**Comment by hchen90** [comment]
这是**CMakeList.txt**的配置问题，主要是因为clang没有rdynamic这个参数，问题已经修正过，请pull最新代码

**Comment by luckypoem** [comment]
在mac上还是不行：

yudeMacBook-Air:jackpot brite$ make
Scanning dependencies of target jackpot
[  8%] Building CXX object src/CMakeFiles/jackpot.dir/client.cpp.o
clang: warning: argument unused during compilation: '-rdynamic' [-Wunused-command-line-argument]
/Users/brite/jackpot/src/client.cpp:148:13: error: use of undeclared identifier
      'select'
    switch (select(_host.socket() + 1, nullptr, &fds, nullptr, &tmv)) {
            ^
/Users/brite/jackpot/src/client.cpp:184:9: error: use of undeclared identifier
      'select'
    if (select(MAX(fd, _fd_cli) + 1, &fds, nullptr, nullptr, &tmv) > 0) {
        ^
2 errors generated.
make[2]: *** [src/CMakeFiles/jackpot.dir/client.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/jackpot.dir/all] Error 2
make: *** [all] Error 2
yudeMacBook-Air:jackpot brite$

不支持mac系统吗

**Comment by hchen90** [comment]
尝试在client.cpp里面添加
#include <sys/select.h>
看是否可以解决问题？此代码目前还没有做对于bsd/mac类系统的适配，所以在这类系统可能会出现更多的问题

**Comment by luckypoem** [comment]
加了那行后，
make显示：
fatal error: 'sys/sysmacros.h' file
      not found
#include <sys/sysmacros.h>

**Comment by hchen90** [comment]
再次拉取最新代码试试

**Comment by luckypoem** [comment]
hi.
这次，Mac上编译成功。
不过服务器上和本地机器上的命令应该各怎么写？

**Comment by luckypoem** [comment]
服务器上，这样对吗：

./jackpot -tip 0.0.0.0 -tport 443 -k private.key -c public.crt -serial mypassword -a 127.0.0.1 -w 1278
显示：
Proxy server is listening on [0.0.0.0:443]
Web server is listening on [127.0.0.1:1278]

Mac机器上的命令该如何写？

**Comment by hchen90** [comment]
都一样的

Proxy server是一个可以跳转到socks5代理的https服务器
Web server就是一个简单的http服务器

> 服务器的配置一般推荐使用配置文件来配置，参考一下doc下的server.conf和client.conf

**Comment by luckypoem** [comment]
hi.

yudeMacBook-Air:src brite$ ./jackpot -config client.conf
Cannot initialized proxy
yudeMacBook-Air:src brite$ 

怎么解决？
感觉这个jackpot不如vssocks好用。

**Comment by hchen90** [comment]
./jackpot -n client.conf

所有的传递参数只有一个字母，[config]表示这是一个附加配置文件路径的意思

```
[main]
; the private key & certificate file are only for test, do not use it in internet. generate a new pair
; by yourself with openssl tool, or query a pair from Lets Encrypt!
private_key=sample.key
certificate=sample.crt
serial=mypassword
timeout=30000
[tls]
; remote proxy server
timeout = 20
ip=0.0.0.0
port=4444
[web]
; remote web server
timeout = 5
ip=0.0.0.0
port=8888
; rootfs.cpio is an archive for all files on web server.
;rootfs = rootfs.cpio
;rootfs=/root/a.cpio
```
上面是服务端的配置，你需要生成一对非对称的密钥和签名（用openssl工具），如果自己有域名的话，你也可以用certbot获取Lets Encrypt的签名证书，获得私钥和证书后替代上面的sample.key和sample.crt，为了方便操作，你可以保存以下shell脚本，以便执行，它会生成对应的密钥和签名：
```
openssl genrsa -out sample.key 2048
openssl rsa -in sample.key -pubout -out sample.pub
openssl req -new -key sample.key -out sample.req -subj "/C=US/ST=NY/L=NY/O=HD/OU=dev/CN=jackpot/emailAddress=yourname@yourmaill.com"
openssl genrsa -out sample.ca 2048
openssl req -new -x509 -days 365 -key sample.ca -out sample.cac -subj "/C=US/ST=NY/L=NY/O=HD/OU=dev/CN=jackpot/emailAddress=yourname@yourmail.com"
openssl x509 -req -days 3650 -in sample.req -CA sample.cac -CAkey sample.ca -CAcreateserial -out sample.crt
```
如果你想让你的代理附加一个小型的静态网站服务器，你可以配置rootfs的值，它指向一个静态网站的cpio包，该cpio归档包含有静态网站的所有文件，启动后你可以用http://127.0.0.1:8888/访问它，也支持https://127.0.0.1:4444/访问。

**Comment by hchen90** [comment]
然后，客户端的配置就相当简单了：
```
[main]
serial=mypassword
timeout=30
[tls]
; remote proxy server
ip = 127.0.0.1
port=4444
[local]
; local socks5 server
ip=0.0.0.0
port=1080
```

**Comment by hchen90** [comment]
jackpot的服务端和客户端区分，通过配置文件启动的是自动区分的，服务端的配置文件里面有web这个节区，客户端没有的，客户端有local节区，服务端是没有的。
jackpot的配置稍微复杂一点，当你要部署到远程服务器上时注意替换上面的127.0.0.1。

**Comment by luckypoem** [comment]
hi.

yudeMacBook-Air:src brite$ ./jackpot -n client.conf
libc++abi.dylib: terminating with uncaught exception of type std::__1::regex_error: One of *?+{ was not preceded by a valid regular expression.
Abort trap: 6
yudeMacBook-Air:src brite$ cat client.conf
[main]
serial=mypassword
timeout=30

[tls]
ip = vps-public-ip
; port 4433 is only for test (should set it to 443)
port=4422

[local]
ip=0.0.0.0
port=1082
yudeMacBook-Air:src brite$

client.conf没问题吧？
怎么解决？

**Comment by hchen90** [comment]
这是因为mac的C++库内的正则表达式和linux的有所不同，mac的不支持某些区配方式，现在的代码已经更新过，再拉一下代码就可以了

**Comment by luckypoem** [comment]
hi.

现在，在Mac上，
yudeMacBook-Air:src brite$ ./jackpot -n client.conf
SOCKS5 server is listening on [0.0.0.0:1082]

[127.0.0.1:52317] new connection
[127.0.0.1:52319] new connection
[127.0.0.1:52320] new connection
[127.0.0.1:52321] new connection
[127.0.0.1:52322] new connection
[127.0.0.1:52317] closing connection
[127.0.0.1:52319] closing connection
[127.0.0.1:52320] closing connection
[127.0.0.1:52321] closing connection
[127.0.0.1:52322] closing connection
[127.0.0.1:52329] new connection
[127.0.0.1:52330] new connection
[127.0.0.1:52331] new connection
[127.0.0.1:52333] new connection
[127.0.0.1:52330] closing connection
[127.0.0.1:52329] closing connection
[127.0.0.1:52333] closing connection
[127.0.0.1:52331] closing connection
[127.0.0.1:52344] new connection
[127.0.0.1:52345] new connection
[127.0.0.1:52346] new connection
[127.0.0.1:52348] new connection
[127.0.0.1:52345] closing connection
[127.0.0.1:52344] closing connection
[127.0.0.1:52348] closing connection
[127.0.0.1:52346] closing connection
[127.0.0.1:52383] new connection
[127.0.0.1:52384] new connection
[127.0.0.1:52385] new connection
[127.0.0.1:52387] new connection
[127.0.0.1:52383] closing connection
[127.0.0.1:52392] new connection
[127.0.0.1:52387] closing connection
[127.0.0.1:52385] closing connection
[127.0.0.1:52392] closing connection
[127.0.0.1:52384] closing connection

在vps上，
root@p1601860745:~/jackpot/src# ./jackpot -n server.conf 
Proxy server is listening on [0.0.0.0:4422]
Web server is listening on [0.0.0.0:8877]

[isp分配给我的本地ip:11130] new connection
[isp分配给我的本地ip:19822] new connection
[isp分配给我的本地ip:55372] new connection
[isp分配给我的本地ip:2165] new connection
[isp分配给我的本地ip:11130] closing connection
[isp分配给我的本地ip:19822] closing connection
[isp分配给我的本地ip:55372] closing connection

翻墙失败，问题出在哪里 ？

**Comment by luckypoem** [comment]
hi.

是不是也要在client.conf的[main]段，加上：
private_key=sample.key
certificate=sample.cert 呢？

服务器上的证书文件和私匙文件不用下载到本地的吗？

**Comment by hchen90** [comment]
客户端不需要

**Comment by luckypoem** [comment]
但是上面的问题出在哪里 ？

**Comment by hchen90** [comment]
服务器端的防火墙端口开放了吗？

如果服务器端口没开放：
```
iptables -I INPUT -p tcp --dport 4422 -j ACCEPT
iptables -I INPUT -p tcp --dport 8877 -j ACCEPT
```

用浏览器https可以访问 https://xxx.xxx.xxx.xxx:4422/吗？（把xxx.xxx.xxx.xxx换成你的服务端ip）

如果配置没有问题，可能是服务器端的ping值太高，可以把timeout的值设置大一点

**Comment by luckypoem** [comment]
刚开始时，不能访问 https://xxx.xxx.xxx.xxx:4422  ，后来在服务器上，运行了：
iptables -I INPUT -p tcp -m tcp --dport 4422 -j ACCEPT 后，可以访问https://xxx.xxx.xxx.xxx:4422 了，

但是运行2边的命令后，还是2边都显示 closing connection

**Comment by hchen90** [comment]
如果可以访问 https://xxx.xxx.xxx.xxx:4422/ 说明应该没有问题了，因为服务已经启动，并且可以访问了。

你用命令方式可以启动吗？
```
./jackpot -i xxx.xxx.xxx.xxx -p 4422 -s 你的密码 -w 1082
```

检查一下客户端的配置[main]的serial要和服务器端对应，[tls]里的ip和port也要和服务器端对应

**Comment by luckypoem** [comment]
hi.

"可以把timeout的值设置大一点",  我把timeout的值设置大一点后，现在可以正常翻墙了。原来 closing connection的提示无关紧要，关键是要把2边的timeout的值设置大一点

**Comment by briteming** [comment]
hi.

我在新的vps上，
root@racknerd-7b97d8:~/jackpot# cmake .
CMake Error at src/CMakeLists.txt:42 (message):
  Searching library: ev - not found
Call Stack (most recent call first):
  src/CMakeLists.txt:46 (check_library)


-- Configuring incomplete, errors occurred!
See also "/root/jackpot/CMakeFiles/CMakeOutput.log".
root@racknerd-7b97d8:~/jackpot# 

怎么解决错误？

**Comment by hchen90** [comment]
一般这种错误你只需安装一下依赖的库即可，libev-dev。

如果你觉得编译很繁琐，只是为了部署使用，可以直接从hub.docker.com上面拉取镜像，用docker容器来运行。

https://hub.docker.com/r/hchen90/jackpot
